import type { ExplorationZone, MapBounds } from "@/src/types";

const fuliMap = "/assets/maps/rehearsal/05-fuli-north-four-gates-v1.png";
const fuliBounds: MapBounds = {
  north: 30.278384705367433,
  south: 30.272575208663397,
  east: 119.99346349010466,
  west: 119.98673650989531,
};

const southGate = { latitude: 30.27463, longitude: 119.99011 };
const eastGate = { latitude: 30.27532, longitude: 119.99109 };
const westGate = { latitude: 30.27532, longitude: 119.98904 };
const northGate = { latitude: 30.27636, longitude: 119.98991 };

export const rehearsalZones: ExplorationZone[] = [
  {
    id: "rehearsal-v2-fuli-east-gate",
    order: 1,
    title: "FULI NORTH · EAST GATE",
    subtitle: "富力中心北区东门 · 微距定位彩排",
    parkingLabel: "富力中心北区南门",
    parkingMapPoint: { x: 401, y: 323 },
    center: { latitude: 30.27548, longitude: 119.9901 },
    routeGeo: [
      southGate,
      { latitude: 30.27471, longitude: 119.99112 },
      eastGate,
    ],
    svgPath: "M401 323 C450 322 507 307 518 264",
    maxLocationAccuracyM: 90,
    accent: "#6f3f25",
    mapKind: "city",
    mapBounds: fuliBounds,
    illustratedMapAsset: fuliMap,
    checkpoints: [
      {
        id: "rehearsal-v2-east-gate-checkpoint",
        label: "富力中心北区 · 东门",
        giftType: "scent",
        location: eastGate,
        unlockRadiusM: 20,
        referenceImage: "/references/scent.svg",
        matchMode: "pose-scene",
        passScore: 0,
        clue: "从南门沿北区建筑外侧向东绕行，抵达舒心路一侧的东门。",
        unlockCopy: "富力中心北区东门坐标已解锁。",
        photoPrompt: "上传一张复刻照片，与参考照片进行匹配。",
        mapPoint: { x: 518, y: 264 },
      },
    ],
  },
  {
    id: "rehearsal-v2-fuli-south-gate",
    order: 2,
    title: "FULI NORTH · SOUTH GATE",
    subtitle: "富力中心北区南门 · 微距定位彩排",
    parkingLabel: "富力中心北区东门",
    parkingMapPoint: { x: 518, y: 264 },
    center: { latitude: 30.27548, longitude: 119.9901 },
    routeGeo: [
      eastGate,
      { latitude: 30.27471, longitude: 119.99112 },
      southGate,
    ],
    svgPath: "M518 264 C507 307 450 322 401 323",
    maxLocationAccuracyM: 90,
    accent: "#6f3f25",
    mapKind: "city",
    mapBounds: fuliBounds,
    illustratedMapAsset: fuliMap,
    checkpoints: [
      {
        id: "rehearsal-v2-south-gate-checkpoint",
        label: "富力中心北区 · 南门",
        giftType: "motion",
        location: southGate,
        unlockRadiusM: 20,
        referenceImage: "/references/motion.svg",
        matchMode: "pose-scene",
        passScore: 0,
        clue: "沿建筑东南角折回众志街一侧，寻找北区南门。",
        unlockCopy: "富力中心北区南门坐标已解锁。",
        photoPrompt: "上传一张复刻照片，与参考照片进行匹配。",
        mapPoint: { x: 401, y: 323 },
      },
    ],
  },
  {
    id: "rehearsal-v2-fuli-west-gate",
    order: 3,
    title: "FULI NORTH · WEST GATE",
    subtitle: "富力中心北区西门 · 微距定位彩排",
    parkingLabel: "富力中心北区南门",
    parkingMapPoint: { x: 401, y: 323 },
    center: { latitude: 30.27548, longitude: 119.9901 },
    routeGeo: [
      southGate,
      { latitude: 30.27454, longitude: 119.98904 },
      westGate,
    ],
    svgPath: "M401 323 C340 325 276 308 274 264",
    maxLocationAccuracyM: 90,
    accent: "#6f3f25",
    mapKind: "city",
    mapBounds: fuliBounds,
    illustratedMapAsset: fuliMap,
    checkpoints: [
      {
        id: "rehearsal-v2-west-gate-checkpoint",
        label: "富力中心北区 · 西门",
        giftType: "sound",
        location: westGate,
        unlockRadiusM: 20,
        referenceImage: "/references/sound.svg",
        matchMode: "pose-scene",
        passScore: 0,
        clue: "从南门沿建筑西侧短距离北行，抵达科凯路一侧的西门。",
        unlockCopy: "富力中心北区西门坐标已解锁。",
        photoPrompt: "上传一张复刻照片，与参考照片进行匹配。",
        mapPoint: { x: 274, y: 264 },
      },
    ],
  },
  {
    id: "rehearsal-v2-fuli-north-gate",
    order: 4,
    title: "FULI NORTH · NORTH GATE",
    subtitle: "富力中心北区北门 · 微距定位彩排",
    parkingLabel: "富力中心北区西门",
    parkingMapPoint: { x: 274, y: 264 },
    center: { latitude: 30.27548, longitude: 119.9901 },
    routeGeo: [
      westGate,
      { latitude: 30.27631, longitude: 119.98903 },
      northGate,
    ],
    svgPath: "M274 264 C274 210 321 174 377 174",
    maxLocationAccuracyM: 90,
    accent: "#6f3f25",
    mapKind: "city",
    mapBounds: fuliBounds,
    illustratedMapAsset: fuliMap,
    checkpoints: [
      {
        id: "rehearsal-v2-north-gate-checkpoint",
        label: "富力中心北区 · 北门",
        giftType: "sparkle",
        location: northGate,
        unlockRadiusM: 20,
        referenceImage: "/references/sparkle.svg",
        matchMode: "pose-scene",
        passScore: 0,
        clue: "绕过建筑西北角，抵达面向文一西路的北门，完成四出口小环线。",
        unlockCopy: "富力中心北区北门坐标已解锁。",
        photoPrompt: "上传一张复刻照片，与参考照片进行匹配。",
        mapPoint: { x: 377, y: 174 },
      },
    ],
  },
];
